### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NicoCG** [3DSemantix/angular-asp.net-core-aad-b2c#4]
Hi @NicolasConstant,

Kindly add the ability to Register and Reset password I would really appreciate it.

**Comment by NicolasConstant** [comment]
Hi, 

The project already have the Register functionality.

For the Reset password, it's an advanced functionality that I feel is out of scope of this proof of concept since it depends on the way your users interact with the app (if they're using Google sign-in for example, you won't be able to provide it).

If you're sure your user is using an AAD Local Account, you just have to provide this URL somewhere in your HTML: 
```
https://login.microsoftonline.com/tfp/{YOUR-TENANT-NAME-HERE}/{YOUR-RESET-PASSWORD-POLICY-NAME-HERE}
``` 

There are a lot of resources online that will explain this very well, like: 
https://codemilltech.com/changing-passwords-and-user-info-with-azure-ad-b2c/
