### ISSUE TITLE
AAD B2C Setup

### ISSUE THREAD

**Issue by luke-browning** [3DSemantix/angular-asp.net-core-aad-b2c#5]
Hi,

I was looking through your example and tried to get it running with a test B2C setup but when I call the GetTokens api I get the following error;

> Invalid Grant: This application does not have sufficient permissions against this web resource to perform the operation.

I was wondering if you could document how the Azure side was set up as I'm a new to B2C!

Thanks

**Comment by NicolasConstant** [comment]
Hi, 

Before using this example you must learn and understand the B2C oauth workflow because one installation from another can be very different and there is no single way to set and use it.

Please look at the documentation about the [OAuth 2.0 authorization code flow in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code) and the [B2C tutorials](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant), it should give you all the needed information to understand the global workflow and settings.

I encourage you to test it on you own on Postman or other tool, to make sure you have all the needed parameters and settings and then set them in this example.

In your case, I may be wrong, but I think you didn't give your application access to your API, check it at B2C/Application/your app/API Access and add the resource and related scopes.
